import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import SearchField from '../components/SearchField'
import axios from "axios"
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home(database) {
  const [limit, setLimit] = useState(6)
  const [offset, setOffset] = useState(0)
  let count = 0

  return (
    <>
      <Head>
        <title>Search Hardware</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SearchField />

        <div className={styles.itemsDisplay}>
          {Array.isArray(database.database) ?

            database.database.map((el, index) => {
              count++
              if (count > limit) { return }
              if (index < offset) {
                ""
              } else {
                return <div className={styles.carditem}>
                  <li>{el.title}</li>
                </div>
              }



            }) :

            console.log(database.database)
          }
        </div>
        <button className={styles.btnvermais} onClick={() => {
          if (offset === database.database.length-1) { return }
          setLimit(limit + 1)
          setOffset(offset + 1)
        }}>ver mais</button>
        <button className={styles.btnretornar} onClick={() => {
          if (offset === 0) {
            return
          }
          setLimit(limit - 1)
          setOffset(offset - 1)
        }}>retornar</button>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const result = await fetch("http://localhost:3000/api/server")
  const resultjson = await result.json()
  return {
    props: {
      database: resultjson
    }
  }
}
